# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: The Europlanet Machine Learning Book
author: The Europlanet ML Team
logo: Europlanet_Machine_Learning_Logo_Standard.png

#######################################################################################
# HTML-specific settings
html:
  use_multitoc_numbering: false

###########################################################################

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
#execute:
#  execute_notebooks: force

#######################################################################################
# Advanced and power-user settings
sphinx:
#  extra_extensions          :   # A list of extra extensions to load by Sphinx.
#    - jupyterbook_latex
  config:                       # key-value pairs to directly over-ride the Sphinx configuration
    html_show_copyright: false
    bibtex_reference_style: author_year

###################################################################
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: europlanet-ml-book.tex

bibtex_bibfiles:
   - references.bib
###################################################################
# Information about where the book exists on the web
# repository:
#  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
# html:
#  use_issues_button: true
#  use_repository_button: true
